# Generated by Django 4.2.4 on 2023-10-12 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('image', models.ImageField(upload_to='media')),
                ('description', models.CharField(blank=True, max_length=500)),
                ('sale_type', models.IntegerField(choices=[(1, 'Sale'), (2, 'Donation')], default=1)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='project.user')),
            ],
        ),
    ]
