# Generated by Django 4.2.4 on 2023-10-15 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_user_zipcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecycleEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recycler', models.CharField(max_length=400)),
                ('date_of', models.DateField()),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('zipcode', models.CharField(max_length=1000)),
                ('instructions', models.CharField(blank=True, max_length=500)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recycleevents', to='project.user')),
            ],
        ),
    ]
