# Generated by Django 4.2.4 on 2023-10-16 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_recycleevent_fee'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RecycleEvent',
            new_name='Recycle_Event',
        ),
    ]
